services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/notebooks
    working_dir: /notebooks
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    restart: unless-stopped
